### ISSUE TITLE
Failed when `python manage.py migrate`

### ISSUE THREAD

**Issue by children1987** [django-cas-ng/django-cas-ng#301] opened 2021-10-28 02:35 UTC
**Platform & Version**
Platform: Windows or Linux or Mac...
django-cas-ng: 4.2.1
Django: 2.2.24
Python: 3.7
CAS Server Software and version: Not involved

**Describe the bug**
Failed when `python manage.py migrate`.

**To Reproduce**
1. 
`
pip install django-cas-ng==4.0.1
`

2.
`
python manage.py migrate
`
Successed!

3. 
`
pip install django-cas-ng==4.2.1
`

4.
`
python manage.py migrate
`
Failed!

**Additional context**
`
(backend) D:\zzp\repo_git\pdsks\backend>python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, books, contenttypes, django_cas_ng, documents, exams, licenses, questions, sessions, sites
, tiantong_uni, trainings, users
Running migrations:
  Applying django_cas_ng.0002_auto_20201023_1400...Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\backend-QOyWBTVn\lib\site-packages\django\db\backends\utils.py", line 84, in _execu
te
    return self.cursor.execute(sql, params)
  File "C:\Users\Administrator\.virtualenvs\backend-QOyWBTVn\lib\site-packages\django\db\backends\mysql\base.py", line 71, in e
xecute
    return self.cursor.execute(query, args)
  File "C:\Users\Administrator\.virtualenvs\backend-QOyWBTVn\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "C:\Users\Administrator\.virtualenvs\backend-QOyWBTVn\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "C:\Users\Administrator\.virtualenvs\backend-QOyWBTVn\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1071, 'Specified key was too long; max key length is 3072 bytes')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 30, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\Administrator\.virtualenvs\backend-QOyWBTVn\lib\site-packages\django\core\management\__init__.py", line 381, i
n execute_from_command_line
    utility.execute()
  File "C:\Users\Administrator\.virtualenvs\backend-QOyWBTVn\lib\site-packages\django\core\management\__init__.py", line 375, i
n execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\Administrator\.virtualenvs\backend-QOyWBTVn\lib\site-packages\django\core\management\base.py", line 323, in ru
n_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\Administrator\.virtualenvs\backend-QOyWBTVn\lib\site-packages\django\core\management\base.py", line 364, in ex
ecute
    output = self.handle(*args, **options)
  File "C:\Users\Administrator\.virtualenvs\backend-QOyWBTVn\lib\site-packages\django\core\management\base.py", line 83, in wra
pped
    res = handle_func(*args, **kwargs)
  File "C:\Users\Administrator\.virtualenvs\backend-QOyWBTVn\lib\site-packages\django\core\management\commands\migrate.py", lin
e 234, in handle
    fake_initial=fake_initial,
  File "C:\Users\Administrator\.virtualenvs\backend-QOyWBTVn\lib\site-packages\django\db\migrations\executor.py", line 117, in
migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "C:\Users\Administrator\.virtualenvs\backend-QOyWBTVn\lib\site-packages\django\db\migrations\executor.py", line 147, in
_migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "C:\Users\Administrator\.virtualenvs\backend-QOyWBTVn\lib\site-packages\django\db\migrations\executor.py", line 245, in
apply_migration
    state = migration.apply(state, schema_editor)
  File "C:\Users\Administrator\.virtualenvs\backend-QOyWBTVn\lib\site-packages\django\db\migrations\migration.py", line 124, in
 apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "C:\Users\Administrator\.virtualenvs\backend-QOyWBTVn\lib\site-packages\django\db\migrations\operations\fields.py", line
 249, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "C:\Users\Administrator\.virtualenvs\backend-QOyWBTVn\lib\site-packages\django\db\backends\base\schema.py", line 535, in
 alter_field
    old_db_params, new_db_params, strict)
  File "C:\Users\Administrator\.virtualenvs\backend-QOyWBTVn\lib\site-packages\django\db\backends\base\schema.py", line 685, in
 _alter_field
    params,
  File "C:\Users\Administrator\.virtualenvs\backend-QOyWBTVn\lib\site-packages\django\db\backends\base\schema.py", line 137, in
 execute
    cursor.execute(sql, params)
  File "C:\Users\Administrator\.virtualenvs\backend-QOyWBTVn\lib\site-packages\django\db\backends\utils.py", line 99, in execut
e
    return super().execute(sql, params)
  File "C:\Users\Administrator\.virtualenvs\backend-QOyWBTVn\lib\site-packages\django\db\backends\utils.py", line 67, in execut
e
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\Administrator\.virtualenvs\backend-QOyWBTVn\lib\site-packages\django\db\backends\utils.py", line 76, in _execu
te_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Administrator\.virtualenvs\backend-QOyWBTVn\lib\site-packages\django\db\backends\utils.py", line 84, in _execu
te
    return self.cursor.execute(sql, params)
  File "C:\Users\Administrator\.virtualenvs\backend-QOyWBTVn\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Administrator\.virtualenvs\backend-QOyWBTVn\lib\site-packages\django\db\backends\utils.py", line 84, in _execu
te
    return self.cursor.execute(sql, params)
  File "C:\Users\Administrator\.virtualenvs\backend-QOyWBTVn\lib\site-packages\django\db\backends\mysql\base.py", line 71, in e
xecute
    return self.cursor.execute(query, args)
  File "C:\Users\Administrator\.virtualenvs\backend-QOyWBTVn\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "C:\Users\Administrator\.virtualenvs\backend-QOyWBTVn\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "C:\Users\Administrator\.virtualenvs\backend-QOyWBTVn\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1071, 'Specified key was too long; max key length is 3072 bytes')

`

**Comment by nikolas** [comment] 2021-11-09 15:26
This is a duplicate of #291

**Closed** 2022-01-20 18:28 UTC
Labels: bug, wontfix
